name: 🚀 Deploy to deploy branch

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Enter the target branch (default: latest)"
        required: true
        default: "latest"

permissions:
  contents: write

jobs:
  branch:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🎉 Push to [deploy/${{ inputs.target_branch }}]
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: deploy/${{ inputs.target_branch }}
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
