name: 🐳🏗️🚀 Build & Deploy docker image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        description: The name of the image
        type: string
      dockerfile:
        required: true
        description: The dockerfile used to build the image
        type: string
      test:
        required: false
        default: true
        description: Whether to test the image
        type: boolean
    secrets:
      DOCKER_TOKEN:
        required: true
        description: API Token for docker hub

permissions:
  contents: read

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  DOCKER_IMAGE_NAME: ${{ inputs.image_name }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 🐳🛠️ Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: 🔐📦 Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Extract metadata (tags, labels)  for Docker
      # https://github.com/docker/metadata-action
      - name: 🐳🧾 Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}

      - name: 🌿 Extract branch name
        id: extract_branch
        run: echo "TAG_NAME=${GITHUB_REF#refs/heads/deploy/}" >> $GITHUB_ENV

      # Test run the container
      - name: 🐳📦 Build and export 'test' to Docker
        if: ${{ inputs.test }}
        uses: docker/build-push-action@v6
        with:
          file: ${{ inputs.dockerfile }}
          load: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🐳🧪Test
        if: ${{ inputs.test }}
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE_NAME }}:test

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: 🐳🚀 Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          file: ${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
